# Generated by Django 5.2.6 on 2025-09-13 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_offer_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="Font Awesome class, e.g., 'fas fa-shipping-fast'", max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Why',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='offer',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.CharField(default='0%', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='sale',
            field=models.CharField(default='No sale', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
