# Generated by Django 5.2.6 on 2025-09-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
    ]
