# Generated by Django 5.2.6 on 2025-09-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_banner_options_remove_banner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_bag',
            field=models.BooleanField(default=False, help_text='Is this category for Bags?'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_shag',
            field=models.BooleanField(default=False, help_text='Is this category for Shags?'),
        ),
    ]
