# Generated by Django 5.2.6 on 2025-09-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_is_bag_category_is_shag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
