# Generated by Django 5.2.6 on 2025-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_shag',
        ),
    ]
