# Generated by Django 5.2.6 on 2025-09-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_is_bag_remove_product_is_shag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
